languageCode = 'en-us'
title = 'Jacob Coughenour'

[Author]
    name = "Jacob Coughenour"
    email = "me@jacobcoughenour.com"

[markup]
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1

[params.meta]
  author = "Jacob Coughenour"
  msColor = "#2e233e"
  iOSColor = "#2e233e"